// Memorable names for devices ("Wobbly Teal Otter"), derived from the device
// id rather than stored and deterministic so the server and every device always agree
const ADJECTIVES = [
  "Bouncy",
  "Bubbly",
  "Cheeky",
  "Chunky",
  "Clumsy",
  "Cranky",
  "Dizzy",
  "Dopey",
  "Fancy",
  "Fluffy",
  "Fuzzy",
  "Giddy",
  "Goofy",
  "Grumpy",
  "Happy",
  "Hasty",
  "Hungry",
  "Jazzy",
  "Jolly",
  "Jumpy",
  "Lanky",
  "Loopy",
  "Lucky",
  "Merry",
  "Moody",
  "Nerdy",
  "Nifty",
  "Nutty",
  "Peppy",
  "Perky",
  "Plucky",
  "Pudgy",
  "Quirky",
  "Rowdy",
  "Rusty",
  "Sassy",
  "Silly",
  "Sleepy",
  "Sneaky",
  "Snooty",
  "Soggy",
  "Spiffy",
  "Spunky",
  "Squishy",
  "Stinky",
  "Sulky",
  "Sunny",
  "Tipsy",
  "Twitchy",
  "Wacky",
  "Wiggly",
  "Wobbly",
  "Zany",
  "Zippy",
  "Breezy",
  "Crafty",
  "Dapper",
  "Frisky",
  "Gutsy",
  "Itchy",
  "Mighty",
  "Rascally",
  "Snappy",
  "Toasty",
];

const COLORS = [
  "Amber",
  "Aqua",
  "Azure",
  "Beige",
  "Black",
  "Blue",
  "Bronze",
  "Brown",
  "Coral",
  "Crimson",
  "Cyan",
  "Gold",
  "Green",
  "Grey",
  "Indigo",
  "Ivory",
  "Jade",
  "Lemon",
  "Lilac",
  "Lime",
  "Magenta",
  "Maroon",
  "Mint",
  "Navy",
  "Olive",
  "Orange",
  "Peach",
  "Pink",
  "Plum",
  "Purple",
  "Red",
  "Ruby",
  "Rust",
  "Sage",
  "Scarlet",
  "Silver",
  "Tan",
  "Teal",
  "Violet",
  "White",
];

const ANIMALS = [
  "Aardvark",
  "Alpaca",
  "Badger",
  "Beaver",
  "Bison",
  "Camel",
  "Cheetah",
  "Chicken",
  "Cobra",
  "Coyote",
  "Crab",
  "Crow",
  "Dingo",
  "Dolphin",
  "Donkey",
  "Duck",
  "Eagle",
  "Eel",
  "Elk",
  "Ferret",
  "Flamingo",
  "Fox",
  "Frog",
  "Gecko",
  "Giraffe",
  "Goat",
  "Goose",
  "Gopher",
  "Hamster",
  "Hedgehog",
  "Heron",
  "Hippo",
  "Hyena",
  "Iguana",
  "Jackal",
  "Koala",
  "Lemur",
  "Llama",
  "Lobster",
  "Lynx",
  "Marmot",
  "Meerkat",
  "Moose",
  "Narwhal",
  "Newt",
  "Octopus",
  "Ostrich",
  "Otter",
  "Owl",
  "Panda",
  "Parrot",
  "Pelican",
  "Penguin",
  "Pigeon",
  "Puffin",
  "Quokka",
  "Rabbit",
  "Raccoon",
  "Salmon",
  "Seal",
  "Sloth",
  "Squid",
  "Toucan",
  "Walrus",
];

const pick = (words: string[], hex: string) =>
  words[parseInt(hex, 16) % words.length];

export function deviceName(id: string): string {
  const hex = id.replace(/-/g, "").toLowerCase(); //skip v4 uuid version/variant bits
  return [
    pick(ADJECTIVES, hex.slice(0, 8)),
    pick(COLORS, hex.slice(20, 26)),
    pick(ANIMALS, hex.slice(26, 32)),
  ].join(" ");
}

const suffix = (id: string) => id.replace(/-/g, "").slice(8, 12).toLowerCase();

// Name collisions are unlikely (~164k combinations) but not impossible, so
// a list shown together falls back to appending part of the id when two
// devices would otherwise look the same.
export function deviceNames(ids: string[]): Map<string, string> {
  const base = new Map(ids.map((id) => [id, deviceName(id)]));
  const uses = new Map<string, number>();
  for (const name of base.values()) uses.set(name, (uses.get(name) ?? 0) + 1);
  return new Map(
    [...base].map(([id, name]) => [
      id,
      uses.get(name)! > 1 ? `${name} (${suffix(id)})` : name,
    ]),
  );
}
